### ISSUE TITLE
Error when requiring

### ISSUE THREAD

**Issue by raine** [ThomWright/flyd-timeInterval#1]
I get this error when doing `require('flyd-timeinterval')`

```
Error: Cannot find module 'babel-runtime/helpers/interop-require-default' from '/Users/rainevi/code/javascript/flyd-playground/node_modules/flyd-timeinterval/dist'
```

```
~/c/j/flyd-playground ❯❯❯ node
> require('flyd-timeinterval')
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
```

**Comment by raine** [comment]
Thanks.

**Comment by ThomWright** [comment]
Should be fixed, can you let me know? If so, I'll probably need to do this for my other modules too. I seem to have misunderstood how to use `babel-runtime`, and it wasn't necessary anyway.

`v0.4.0` should be on NPM once the build finishes.
